<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="InputViewModels\**" />
    <EmbeddedResource Remove="InputViewModels\**" />
    <None Remove="InputViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkoutApp.Core\WorkoutApp.Core.csproj" />
    <ProjectReference Include="..\WorkoutApp.Infrastructure\WorkoutApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
