<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkoutApp.Core\WorkoutApp.Core.csproj" />
    <ProjectReference Include="..\WorkoutApp.Infrastructure\WorkoutApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="InputViewModels\TrainingPlanTrainingInputModels\" />
    <Folder Include="InputViewModels\TrainingExercisesInputModels\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
